spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/naver
            authorization-grant-type: authorization_code
            client-secret: v4YhMSG9xK
            scope: name,email
            client-name: naver
            client-id: Ia82IfMFmMw4wctdi_Lh
          google:
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-id: 201727493399-6i9742pdtp4nk5df4huvfuql2sg5581t.apps.googleusercontent.com
            client-name: google
            scope: profile,email
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token


  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console  # H2 Console Path
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    #MODE=MYSQL
    url: jdbc:h2:mem:db;
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    # ????? sql?? ?? ???? ???? ?? ? ?? ?? ??
    defer-datasource-initialization: true
    properties:
      hibernate:
        #        show_sql: true
        #        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: dakljlfnVDLKFEoianvadlkVDAPIFeqjpfSNLDVlkadfjLQEAPIfNSLDK

logging:
  level:
    org:
      springframework:
        security: DEBUG


