spring:
  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console  # H2 Console Path
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    #MODE=MYSQL
    url: jdbc:h2:mem:db;
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    # ????? sql?? ?? ???? ???? ?? ? ?? ?? ??
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect