spring:
#  web:
#    resources:
#      static-locations: classpath:/static/,file:src/main/resources/static/
  mail:
    host: smtp.gmail.com  # Gmail의 SMTP 서버 호스트
    port: 587 # Gmail SMTP 서버는 587번 포트를 사용
    username: sangwopark19@gmail.com
    password: gtxn qsff jtjt kplt
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버에 인증 필요한 경우 true로 지정 Gmail은 요구함
          starttls:
            enable: true # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정
            required: true
          connectiontimeout: 5000 # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          timeout: 5000 # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간
          writetimeout: 5000 # 클라이언트가 작업을 완료하는데 대기해야 하는 시간
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분 이메일 인증 코드의 만료 시간(Millisecond)
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-secret: v4YhMSG9xK
            scope: name,email
            client-name: naver
            client-id: Ia82IfMFmMw4wctdi_Lh
          google:
            client-secret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-id: 201727493399-6i9742pdtp4nk5df4huvfuql2sg5581t.apps.googleusercontent.com
            client-name: google
            scope: profile,email
          kakao:
            client-id: b3dc72b320077ac7eb2191fa816ba06a
            client-secret: e8BHZuOEgU6wVkgWWNkjw1SnvqXMQ9HS
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
          github:
            client-id: Ov23liphOxVlVdkvIju7
            client-secret: 3b7d37704f9f5a804f2ad8242f4d9e536d2a56a1
            scope:
              - read:user
              - user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            client-name: GitHub
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  # H2 Setting Info
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console  # H2 Console Path
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver
    #MODE=MYSQL
    url: jdbc:h2:mem:db;
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    # ????? sql?? ?? ???? ???? ?? ? ?? ?? ??
    defer-datasource-initialization: true
    properties:
      hibernate:
        #        show_sql: true
        #        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: dakljlfnVDLKFEoianvadlkVDAPIFeqjpfSNLDVlkadfjLQEAPIfNSLDK

logging:
  level:
    org:
      springframework:
        security: debug

file:
  upload-dir: ${user.home}/uploads

server:
  port: 8080